ci: combine everything into a single matrix build
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -11,6 +11,7 @@ variables:
   REGISTRY_BASE: "registry.gfnd.rcn-ee.org:5000/ci"
   RUN_CI_GIT_UPDATE: "true"
   RUN_CI_DT_SCHEMA_CHECKER: "true"
+  DEBIAN_VERSION_ARTIFACTS: "13"
 
 stages:
   - build
@@ -26,7 +27,7 @@ before_script:
   - . version.sh && echo $BRANCH
 
 after_script:
-    - rm -rf $CI_PROJECT_DIR/KERNEL/
+  - rm -rf $CI_PROJECT_DIR/KERNEL/
 
 .script_fragments:
   setup_dt_schema:
@@ -48,7 +49,7 @@ after_script:
   cleanup_ccache:
     - ./tools/ci-cleanup-ccache.sh
 
-.base_build:
+.unified_build_template:
   stage: build
   tags:
     - docker-amd64
@@ -57,68 +58,83 @@ after_script:
     - if: $CI_COMMIT_TAG
       when: never
     - when: always
-
-.debian_build_template:
-  extends: .base_build
-  variables:
-    SYSTEM_SH_SRC: "system.sh.gitlab"
-    CHECK_FILE: "deploy/linux-image-*.deb"
   cache:
-    key: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-$CI_DISTRO-amd64"
-    paths:
-      - ccache.tar.zst
-  script:
-    - !reference [.script_fragments, setup_dt_schema]
-    - !reference [.script_fragments, setup_ccache]
-    - cp -v $SYSTEM_SH_SRC system.sh
-    - ./build_deb.sh
-    - du -sh $CHECK_FILE || exit 1
-    - !reference [.script_fragments, cleanup_ccache]
-
-.kernel_build_template:
-  extends: .base_build
-  variables:
-    SYSTEM_SH_SRC: "system.sh.gitlab.crosstool"
-    CHECK_FILE: "KERNEL/$KERNEL_IMAGE"
-  cache:
-    key: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_DISTRO-amd64"
+    key: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_DISTRO-$VERSION-amd64"
     paths:
       - ccache.tar.zst
       - dl/*.tar.xz
   script:
+    - !reference [.script_fragments, setup_dt_schema]
     - !reference [.script_fragments, setup_ccache]
     - cp -v $SYSTEM_SH_SRC system.sh
-    - ./build_kernel.sh
-    - du -sh $CHECK_FILE || exit 1
+    
+    # --- 1. PREPARE BUILD CONFIGURATION ---
+    - |
+      if [ "$CI_DISTRO" = "debian" ]; then
+        BUILD_SCRIPT="build_deb.sh"
+        CHECK_PATH="$CHECK_FILE"
+        echo "Mode: Debian Build"
+      else
+        BUILD_SCRIPT="build_kernel.sh"
+        CHECK_PATH="KERNEL/$KERNEL_IMAGE"
+        echo "Mode: Kernel Build ($CI_DISTRO)"
+      fi
+      echo "Running $BUILD_SCRIPT..."
+
+    # --- 2. EXECUTE BUILD ---
+    - ./$BUILD_SCRIPT
+
+    # --- 3. POST-BUILD: VERIFICATION & ARTIFACT MANAGEMENT ---
+    - |
+      echo "Verifying: $CHECK_PATH"
+      if [ -f "$CHECK_PATH" ] || [ -d "$CHECK_PATH" ]; then
+        echo "Success: $CHECK_PATH found."
+        du -sh "$CHECK_PATH"
+      else
+        echo "Error: $CHECK_PATH NOT FOUND!"
+        exit 1
+      fi
+
+      # If it's a Debian build and NOT the version we want to keep, hide the file
+      if [ "$CI_DISTRO" = "debian" ]; then
+        export DEBIAN_VERSION_ARTIFACTS="$DEBIAN_VERSION_ARTIFACTS"
+        if [ "$VERSION" != "$DEBIAN_VERSION_ARTIFACTS" ]; then
+          echo "Version $VERSION is not $DEBIAN_VERSION_ARTIFACTS: Hiding debian artifacts."
+          mkdir -p .hidden_artifacts
+          mv "$CHECK_PATH" .hidden_artifacts/ || true
+        fi
+      fi
+    # ---------------------------------------------------------
+
     - !reference [.script_fragments, cleanup_ccache]
 
-build-debian-13-amd64:
-  extends: .debian_build_template
-  image: $REGISTRY_BASE/beagle-devscripts-kernel-debian-13-amd64:latest
-  variables:
-    TARGET_LOCK_NAME: "lock-debian-13-$CI_COMMIT_BRANCH"
-    CI_DISTRO: "13"
+build-all:
+  extends: .unified_build_template
+  image: $REGISTRY_BASE/beagle-devscripts-kernel-$CI_DISTRO-$VERSION-amd64:latest
   artifacts:
     expire_in: 1 week
-    name: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-13-$CI_JOB_ID"
+    name: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_DISTRO-$VERSION-$CI_JOB_ID"
     paths:
       - "deploy/linux-image-*.deb"
-
-build-debian-14-amd64:
-  extends: .debian_build_template
-  image: $REGISTRY_BASE/beagle-devscripts-kernel-debian-14-amd64:latest
-  variables:
-    TARGET_LOCK_NAME: "lock-debian-14-$CI_COMMIT_BRANCH"
-    CI_DISTRO: "14"
-
-build-kernel:
-  extends: .kernel_build_template
   parallel:
     matrix:
+      # --- DEBIAN ---
+      - CI_DISTRO: "debian"
+        VERSION: "13"
+        SYSTEM_SH_SRC: "system.sh.gitlab"
+        CHECK_FILE: "deploy/linux-image-*.deb"
+        TARGET_LOCK_NAME: "lock-debian-13-$CI_COMMIT_BRANCH"
+      - CI_DISTRO: "debian"
+        VERSION: "14"
+        SYSTEM_SH_SRC: "system.sh.gitlab"
+        CHECK_FILE: "deploy/linux-image-*.deb"
+        TARGET_LOCK_NAME: "lock-debian-14-$CI_COMMIT_BRANCH"
+      # --- KERNEL ---
       - CI_DISTRO: "ubuntu"
         VERSION: "26.04"
+        SYSTEM_SH_SRC: "system.sh.gitlab.crosstool"
+        TARGET_LOCK_NAME: "lock-ubuntu-$CI_COMMIT_BRANCH"
       - CI_DISTRO: "fedora"
         VERSION: "44"
-  image: $REGISTRY_BASE/beagle-devscripts-kernel-$CI_DISTRO-$VERSION-amd64:latest
-  variables:
-    TARGET_LOCK_NAME: "lock-$CI_DISTRO-$CI_COMMIT_BRANCH"
+        SYSTEM_SH_SRC: "system.sh.gitlab.crosstool"
+        TARGET_LOCK_NAME: "lock-fedora-$CI_COMMIT_BRANCH"
