scripts: resync all build scripts
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,69 +1,126 @@
+# SPDX-FileCopyrightText: Robert Nelson <robertcnelson@gmail.com>
+# SPDX-License-Identifier: MIT
+#
+# You can find the Docker source files at https://openbeagle.org/beagleboard/ci-docker-images
+
+variables:
+  TRANSFER_METER_FREQUENCY: "5s"
+  GIT_STRATEGY: "clone"
+  GIT_DEPTH: 1
+  KERNEL_IMAGE: "arch/arm/boot/zImage"
+  REGISTRY_BASE: "registry.gfnd.rcn-ee.org:5000/ci"
+  RUN_CI_GIT_UPDATE: "false"
+  RUN_CI_DT_SCHEMA_CHECKER: "false"
+
+stages:
+  - build
+
 before_script:
   - export PATH=/usr/lib/ccache:$PATH
-  - echo "Acquire::http::Proxy \"http://192.168.1.10:3142\";" > /etc/apt/apt.conf.d/00aptproxy
-  - apt-get update
-  - apt-get dist-upgrade -yq
+  - export CCACHE_DIR=/dev/shm/my-ccache-in-memory
+  - export DEBEMAIL="$GITLAB_USER_EMAIL"
+  - export DEBFULLNAME="$GITLAB_USER_NAME"
+  - df -h /dev/shm
   - git config --global user.email "$GITLAB_USER_EMAIL"
   - git config --global user.name "$GITLAB_USER_NAME"
+  - . version.sh && echo $BRANCH
 
-build-debian-12-amd64:
-  image: robertcnelson/beagle-devscripts-kernel-debian-12-amd64:latest
-  # https://openbeagle.org/beagleboard/ci-docker-images
-  cache:
-    key: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-12-amd64"
-    paths:
-      - ccache.tar.lz4
+after_script:
+  - rm -rf $CI_PROJECT_DIR/KERNEL/
+
+.script_fragments:
+  setup_dt_schema:
+    - |
+      if [ "$RUN_CI_DT_SCHEMA_CHECKER" = "true" ]; then
+        export PATH=/root/.local/bin:$PATH
+        ./tools/ci-dt-schema.sh
+      else
+        echo "Skipping ci-dt-schema.sh because RUN_CI_DT_SCHEMA_CHECKER is not true"
+      fi
+  setup_ccache:
+    - |
+      if [ "$RUN_CI_GIT_UPDATE" = "true" ]; then
+        ./tools/ci-git.sh
+      else
+        echo "Skipping ci-git.sh because RUN_CI_GIT_UPDATE is not true"
+      fi
+    - ./tools/ci-setup-ccache.sh
+  cleanup_ccache:
+    - ./tools/ci-cleanup-ccache.sh
+
+.unified_build_template:
+  stage: build
   tags:
     - docker-amd64
-  stage: build
-  script:
-    - . version.sh && echo $BRANCH
-    - mkdir -p /root/.cache/ccache/ || true
-    - tar --use-compress-program=lz4 -xf ccache.tar.lz4 -C / || true
-    - ccache -M 2G
-    - ccache -z
-    - cp -v system.sh.gitlab system.sh
-    - ./build_deb.sh
-    - du -sh deploy/linux-image-*.deb || exit 1
-    - ccache -sv
-    - tar --use-compress-program=lz4 -cf ccache.tar.lz4 /root/.cache/ccache/
+  resource_group: lock-$CI_DISTRO-$VERSION-$CI_COMMIT_BRANCH
   rules:
     - if: $CI_COMMIT_TAG
       when: never
     - when: always
-  artifacts:
-    expire_in: 1 week
-    name: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-12-$CI_JOB_ID"
-    paths:
-      - "deploy/linux-image-*.deb"
-
-build-debian-13-amd64:
-  image: robertcnelson/beagle-devscripts-kernel-debian-13-amd64:latest
-  # https://openbeagle.org/beagleboard/ci-docker-images
   cache:
-    key: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-13-amd64"
+    key: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_DISTRO-$VERSION-amd64"
     paths:
-      - ccache.tar.lz4
-  tags:
-    - docker-amd64
-  stage: build
+      - ccache.tar.zst
+      - dl/*.tar.xz
   script:
-    - . version.sh && echo $BRANCH
-    - mkdir -p /root/.cache/ccache/ || true
-    - tar --use-compress-program=lz4 -xf ccache.tar.lz4 -C / || true
-    - ccache -M 2G
-    - ccache -z
-    - cp -v system.sh.gitlab system.sh
-    - ./build_deb.sh
-    - du -sh deploy/linux-image-*.deb || exit 1
-    - ccache -sv
-    - tar --use-compress-program=lz4 -cf ccache.tar.lz4 /root/.cache/ccache/
-  rules:
-    - if: $CI_COMMIT_TAG
-      when: never
-    - when: always
+    - !reference [.script_fragments, setup_dt_schema]
+    - !reference [.script_fragments, setup_ccache]
+    
+    # --- 1. PREPARE BUILD CONFIGURATION & SOURCE FILES ---
+    - |
+      if [ "$CI_DISTRO" = "debian" ]; then
+        BUILD_SCRIPT="build_deb.sh"
+        SRC_FILE="system.sh.gitlab"
+        echo "Mode: Debian Build"
+      else
+        BUILD_SCRIPT="build_kernel.sh"
+        CHECK_PATH="KERNEL/$KERNEL_IMAGE"
+        SRC_FILE="system.sh.gitlab.crosstool"
+        echo "Mode: Kernel Build ($CI_DISTRO)"
+      fi
+      
+      echo "Using source file: $SRC_FILE"
+      cp -v "$SRC_FILE" system.sh
+      echo "Running $BUILD_SCRIPT..."
+
+    # --- 2. EXECUTE BUILD ---
+    - ./$BUILD_SCRIPT
+
+    # --- 3. POST-BUILD: VERIFICATION & ARTIFACT MANAGEMENT ---
+    - |
+      if [ "$CI_DISTRO" = "debian" ]; then
+        # --- DEBIAN SPECIFIC LOGIC ---
+        ls deploy/linux-image-*.deb >/dev/null 2>&1 && du -sh deploy/linux-image-*.deb || { echo "Error: No Debian artifacts found!"; exit 1; }
+      else
+        # --- STANDARD KERNEL/OTHER LOGIC ---
+        echo "Verifying: $CHECK_PATH"
+        if [ -e "$CHECK_PATH" ]; then
+          echo "Success: $CHECK_PATH found."
+          du -sh "$CHECK_PATH"
+        else
+          echo "Error: $CHECK_PATH NOT FOUND!"
+          exit 1
+        fi
+      fi
+    # ---------------------------------------------------------
+
+    - !reference [.script_fragments, cleanup_ccache]
+
+build-all:
+  extends: .unified_build_template
+  image: $REGISTRY_BASE/beagle-devscripts-kernel-$CI_DISTRO-$VERSION-amd64:latest
   artifacts:
     expire_in: 1 week
-    name: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-debian-13-$CI_JOB_ID"
+    name: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_DISTRO-$VERSION-$CI_JOB_ID"
     paths:
       - "deploy/linux-image-*.deb"
+  parallel:
+    matrix:
+      # --- DEBIAN ---
+      - CI_DISTRO: "debian"
+        VERSION: "13"
+      # --- KERNEL ---
+      - CI_DISTRO: "ubuntu"
+        VERSION: "26.04"
+      - CI_DISTRO: "fedora"
+        VERSION: "44"
