4.4.145-bone-rt-r23 release
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/patches/packaging/0001-packaging-sync-builddeb-changes.patch b/patches/packaging/0001-packaging-sync-builddeb-changes.patch
--- a/patches/packaging/0001-packaging-sync-builddeb-changes.patch
+++ b/patches/packaging/0001-packaging-sync-builddeb-changes.patch
@@ -1,15 +1,116 @@
-From 8d163f6532c153de8241a45e6834c5cb9633a0e4 Mon Sep 17 00:00:00 2001
+From a2325c3df0da7127012f48b0b24c37f655b3c971 Mon Sep 17 00:00:00 2001
 From: Robert Nelson <robertcnelson@gmail.com>
-Date: Sat, 20 May 2017 11:15:43 -0500
+Date: Mon, 30 Jul 2018 13:55:47 -0500
 Subject: [PATCH] packaging: sync builddeb changes
 
 Signed-off-by: Robert Nelson <robertcnelson@gmail.com>
 ---
- scripts/package/builddeb | 39 ++++++++++++++++++++++++++-------------
- 1 file changed, 26 insertions(+), 13 deletions(-)
+ scripts/package/Makefile | 46 +++++++++++++++++++++++++++-------------
+ scripts/package/builddeb | 44 +++++++++++++++++++++++++-------------
+ 2 files changed, 60 insertions(+), 30 deletions(-)
 
+diff --git a/scripts/package/Makefile b/scripts/package/Makefile
+index 52917fb8e0c5..9fbcf5ed0ca7 100644
+--- a/scripts/package/Makefile
++++ b/scripts/package/Makefile
+@@ -32,10 +32,14 @@ MKSPEC     := $(srctree)/scripts/package/mkspec
+ 
+ quiet_cmd_src_tar = TAR     $(2).tar.gz
+       cmd_src_tar = \
++set -e; \
+ if test "$(objtree)" != "$(srctree)"; then \
+-	echo "Building source tarball is not possible outside the"; \
+-	echo "kernel source tree. Don't set KBUILD_OUTPUT, or use the"; \
+-	echo "binrpm-pkg or bindeb-pkg target instead."; \
++	echo >&2; \
++	echo >&2 "  ERROR:"; \
++	echo >&2 "  Building source tarball is not possible outside the"; \
++	echo >&2 "  kernel source tree. Don't set KBUILD_OUTPUT, or use the"; \
++	echo >&2 "  binrpm-pkg or bindeb-pkg target instead."; \
++	echo >&2; \
+ 	false; \
+ fi ; \
+ $(srctree)/scripts/setlocalversion --save-scmversion; \
+@@ -45,26 +49,22 @@ rm -f $(objtree)/.scmversion
+ 
+ # rpm-pkg
+ # ---------------------------------------------------------------------------
+-rpm-pkg rpm: FORCE
++rpm-pkg: FORCE
+ 	$(MAKE) clean
+ 	$(CONFIG_SHELL) $(MKSPEC) >$(objtree)/kernel.spec
+ 	$(call cmd,src_tar,$(KERNELPATH),kernel.spec)
+-	$(CONFIG_SHELL) $(srctree)/scripts/mkversion > $(objtree)/.tmp_version
+-	mv -f $(objtree)/.tmp_version $(objtree)/.version
+-	rpmbuild $(RPMOPTS) --target $(UTS_MACHINE) -ta $(KERNELPATH).tar.gz
+-	rm $(KERNELPATH).tar.gz kernel.spec
++	+rpmbuild $(RPMOPTS) --target $(UTS_MACHINE) -ta $(KERNELPATH).tar.gz \
++	--define='_smp_mflags %{nil}'
+ 
+ # binrpm-pkg
+ # ---------------------------------------------------------------------------
+ binrpm-pkg: FORCE
+ 	$(MAKE) KBUILD_SRC=
+ 	$(CONFIG_SHELL) $(MKSPEC) prebuilt > $(objtree)/binkernel.spec
+-	$(CONFIG_SHELL) $(srctree)/scripts/mkversion > $(objtree)/.tmp_version
+-	mv -f $(objtree)/.tmp_version $(objtree)/.version
+-
+-	rpmbuild $(RPMOPTS) --define "_builddir $(objtree)" --target \
++	+rpmbuild $(RPMOPTS) --define "_builddir $(objtree)" --target \
+ 		$(UTS_MACHINE) -bb $(objtree)/binkernel.spec
+-	rm binkernel.spec
++
++clean-files += $(objtree)/*.spec
+ 
+ # Deb target
+ # ---------------------------------------------------------------------------
+@@ -98,6 +98,21 @@ bindeb-pkg: FORCE
+ 
+ clean-dirs += $(objtree)/debian/
+ 
++# snap-pkg
++# ---------------------------------------------------------------------------
++snap-pkg: FORCE
++	rm -rf $(objtree)/snap
++	mkdir $(objtree)/snap
++	$(MAKE) clean
++	$(call cmd,src_tar,$(KERNELPATH))
++	sed "s@KERNELRELEASE@$(KERNELRELEASE)@; \
++		s@SRCTREE@$(shell realpath $(KERNELPATH).tar.gz)@" \
++		$(srctree)/scripts/package/snapcraft.template > \
++		$(objtree)/snap/snapcraft.yaml
++	cd $(objtree)/snap && \
++	snapcraft --target-arch=$(UTS_MACHINE)
++
++clean-dirs += $(objtree)/snap/
+ 
+ # tarball targets
+ # ---------------------------------------------------------------------------
+@@ -117,12 +132,12 @@ quiet_cmd_perf_tar = TAR
+       cmd_perf_tar = \
+ git --git-dir=$(srctree)/.git archive --prefix=$(perf-tar)/         \
+ 	HEAD^{tree} $$(cd $(srctree);                               \
+-		       echo $$(cat $(srctree)/tools/perf/MANIFEST)) \
++		       echo $$(cat tools/perf/MANIFEST)) \
+ 	-o $(perf-tar).tar;                                         \
+ mkdir -p $(perf-tar);                                               \
+ git --git-dir=$(srctree)/.git rev-parse HEAD > $(perf-tar)/HEAD;    \
+ (cd $(srctree)/tools/perf;                                          \
+-util/PERF-VERSION-GEN ../../$(perf-tar)/ 2>/dev/null);              \
++util/PERF-VERSION-GEN $(CURDIR)/$(perf-tar)/);              \
+ tar rf $(perf-tar).tar $(perf-tar)/HEAD $(perf-tar)/PERF-VERSION-FILE; \
+ rm -r $(perf-tar);                                                  \
+ $(if $(findstring tar-src,$@),,                                     \
+@@ -142,6 +157,7 @@ help: FORCE
+ 	@echo '  binrpm-pkg          - Build only the binary kernel RPM package'
+ 	@echo '  deb-pkg             - Build both source and binary deb kernel packages'
+ 	@echo '  bindeb-pkg          - Build only the binary kernel deb package'
++	@echo '  snap-pkg            - Build only the binary kernel snap package (will connect to external hosts)'
+ 	@echo '  tar-pkg             - Build the kernel as an uncompressed tarball'
+ 	@echo '  targz-pkg           - Build the kernel as a gzip compressed tarball'
+ 	@echo '  tarbz2-pkg          - Build the kernel as a bzip2 compressed tarball'
 diff --git a/scripts/package/builddeb b/scripts/package/builddeb
-index 6c3b038ef40d..172be74043c5 100755
+index 6c3b038ef40d..f947e76a7d84 100755
 --- a/scripts/package/builddeb
 +++ b/scripts/package/builddeb
 @@ -26,6 +26,8 @@ create_package() {
@@ -99,20 +200,23 @@ index 6c3b038ef40d..172be74043c5 100755
  Architecture: any
  Description: User Mode Linux kernel, version $version
   User-mode Linux is a port of the Linux kernel to its own system call
-@@ -310,7 +320,6 @@ else
+@@ -310,9 +320,9 @@ else
  	cat <<EOF >> debian/control
  
  Package: $packagename
 -Provides: linux-image, linux-image-2.6, linux-modules-$version
  Suggests: $fwpackagename
  Architecture: any
++Depends: initramfs-tools
  Description: Linux kernel, version $version
-@@ -322,10 +331,16 @@ fi
+  This package contains the Linux kernel, modules and corresponding other
+  files, version: $version.
+@@ -322,10 +332,16 @@ fi
  
  # Build kernel header package
  (cd $srctree; find . -name Makefile\* -o -name Kconfig\* -o -name \*.pl) > "$objtree/debian/hdrsrcfiles"
 -(cd $srctree; find arch/$SRCARCH/include include scripts -type f) >> "$objtree/debian/hdrsrcfiles"
-+(cd $srctree; find arch/*/include include scripts -type f) >> "$objtree/debian/hdrsrcfiles"
++(cd $srctree; find arch/*/include include scripts -type f -o -type l) >> "$objtree/debian/hdrsrcfiles"
  (cd $srctree; find arch/$SRCARCH -name module.lds -o -name Kbuild.platforms -o -name Platform) >> "$objtree/debian/hdrsrcfiles"
  (cd $srctree; find $(find arch/$SRCARCH -name include -o -name scripts -type d) -type f) >> "$objtree/debian/hdrsrcfiles"
 +if grep -q '^CONFIG_STACK_VALIDATION=y' $KCONFIG_CONFIG ; then
@@ -125,7 +229,7 @@ index 6c3b038ef40d..172be74043c5 100755
  destdir=$kernel_headers_dir/usr/src/linux-headers-$version
  mkdir -p "$destdir"
  (cd $srctree; tar -c -f - -T -) < "$objtree/debian/hdrsrcfiles" | (cd $destdir; tar -xf -)
-@@ -337,7 +352,6 @@ rm -f "$objtree/debian/hdrsrcfiles" "$objtree/debian/hdrobjfiles"
+@@ -337,7 +353,6 @@ rm -f "$objtree/debian/hdrsrcfiles" "$objtree/debian/hdrobjfiles"
  cat <<EOF >> debian/control
  
  Package: $kernel_headers_packagename
@@ -133,7 +237,7 @@ index 6c3b038ef40d..172be74043c5 100755
  Architecture: any
  Description: Linux kernel headers for $KERNELRELEASE on \${kernel:debarch}
   This package provides kernel header files for $KERNELRELEASE on \${kernel:debarch}
-@@ -395,7 +409,6 @@ if [ -n "$BUILD_DEBUG" ] ; then
+@@ -395,7 +410,6 @@ if [ -n "$BUILD_DEBUG" ] ; then
  
  Package: $dbg_packagename
  Section: debug
@@ -141,6 +245,18 @@ index 6c3b038ef40d..172be74043c5 100755
  Architecture: any
  Description: Linux kernel debugging symbols for $version
   This package will come in handy if you need to debug the kernel. It provides
+@@ -429,9 +443,9 @@ EOF
+ 	dpkg-source -cdebian/control -ldebian/changelog --format="3.0 (custom)" --target-format="3.0 (quilt)" \
+ 		-b / ../${sourcename}_${version}.orig.tar.gz  ../${sourcename}_${packageversion}.debian.tar.gz
+ 	mv ${sourcename}_${packageversion}*dsc ..
+-	dpkg-genchanges > ../${sourcename}_${packageversion}_${debarch}.changes
++	dpkg-genchanges -Vkernel:debarch="${debarch}" > ../${sourcename}_${packageversion}_${debarch}.changes
+ else
+-	dpkg-genchanges -b > ../${sourcename}_${packageversion}_${debarch}.changes
++	dpkg-genchanges -b -Vkernel:debarch="${debarch}" > ../${sourcename}_${packageversion}_${debarch}.changes
+ fi
+ 
+ exit 0
 -- 
-2.11.0
+2.18.0
 
